ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.nxzef.wc.ApplicationKt.module ]
    }
}

smtp {
    host = ""
    host = ${?SMTP_HOST}
    port = "587"
    port = ${?SMTP_PORT}
    username = ""
    username = ${?SMTP_USERNAME}
    password = ""
    password = ${?SMTP_PASSWORD}
    from = ""
    from = ${?SMTP_FROM}
}
